### ISSUE TITLE
Textpredictor issue on latest version

### ISSUE THREAD

**Issue by JumpIfZero** [JumpIfZero/public-wiki-and-bugs#5]
**Describe the bug**
Autocomplete that returns multiple matches adds all of them to the editor sometimes

**Steps to Reproduce / how did it happen**
Press tab to autocomplete
Happens randomly

**Expected behavior**
Only current match is entered

**Screenshots**
https://i.imgur.com/0mO66ZA.png

**Device:**
- Kittykeys v2.1.0, did not happen in previous versions

**Comment by JimmyJamJar** [comment]
Occurs when:
"Incorrect syntax" window appears and "OK" is clicked, when typing it will try to autocomplete multiple things at once

**Comment by JumpIfZero** [comment]
Fixed in Kittykeys v3.0.0
