### ISSUE TITLE
MAX INT DISTANCE command - Auto-reported via JZbot by v.o.s.s.

### ISSUE THREAD

**Issue by JumpIfZero** [JumpIfZero/public-wiki-and-bugs#51]
Will change the MAX int. dist. setting.

Helpful for more versatile scripts. 
Currently have to go in manually and change setting when switching between scripts. 
This can be cumbersome and break other scripts if you forget to change. 

ie;  The command in script A would change distance to 5 temporarily via command ('MAXDISTANCE 5') while killing NPCs
-> Then can change back to larger number ('MAXDISTANCE 100') before executing script B (which requires a larger distance)

**Comment by ChandlerFerry** [comment]
Easiest example for my brain:
1. Change max distance to 1, Thieve a stall
2. Change max distance to 104, Bank

**Comment by TwistedModding** [comment]
+ to this, would make manual override scripts more versatile.

**Comment by JumpIfZero** [comment]
KittyKeys v10.1.0
